### ISSUE TITLE
prepare_for_timelineA() with default arguments creates an incorrect visual

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot#169]
When rendering README I noticed that when running prepare_for_timelineA() with only necessary arguments specified I obtain a visual that is incorrect (see image below).

![image](https://user-images.githubusercontent.com/26434113/119662816-18e16900-be32-11eb-8219-ad41cf13a846.png)

The correct visual should be similar to this one (without the dashed lines potentially):

![image](https://user-images.githubusercontent.com/26434113/119662971-3b738200-be32-11eb-94b6-43ae97c3a253.png)

**Comment by maurolepore** [comment]
@MonikaFu, if I understand correctly you expected the `x` axis to start at year 2020 but instead it starts before that. This is because the default `year_start = 0`. Which default should we use?

``` r
library(r2dii.plot.static)

# By default `year_start = 0`. Should we change the default? To what?
formals(prepare_for_timelineA)$year_start
#> [1] 0

sda_target %>% 
  prepare_for_timelineA(sector_filter = "cement") %>% 
  plot_timelineC()
```

![](https://i.imgur.com/e75uUhG.png)

``` r
sda_target %>% 
  prepare_for_timelineA(sector_filter = "cement", year_start = 2020) %>% 
  plot_timelineC()
```

![](https://i.imgur.com/cOyWPF5.png)

<sup>Created on 2021-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by MonikaFu** [comment]
Ah, I see. I can have a look into that. My intention was to use interval (0, Inf) for filtering which would essentially result in min and max of the data to be limits. But apparently this is not the case.
