### ISSUE TITLE
Re-think using release branch for building package website

### ISSUE THREAD

**Issue by MonikaFu** [2DegreesInvesting/r2dii.plot#460]
Currently, the GH pages website of the package points to the release version, and only if the user knows the address of the development version they can see the most recent version of the website: https://2degreesinvesting.github.io/r2dii.plot/dev/articles/r2dii-plot.html

The drawback I see with the current approach is that we need a new release to just add clarifying articles to the website without new features added to the package. Of course, the downside of using the dev version as the main version of the website is that if we do implement and document new features on dev, it might be misleading for the users who downloaded the package from CRAN…

I see options:
1. keep the release website version as the main version but add a link easily pointing to the dev website
2. change the main website version to be the dev and add a link pointing back to the release one 

Personally, I like option 2 more because when the user accesses the website from GitHub (which I assume is more often the case) - the code and documentation on the web coincide. I might be wrong in this assumption, though.

@AlexAxthelm @maurolepore I would be interested to hear your thoughts on this.

**Comment by maurolepore** [comment]
For packages on CRAN I prefer option 1:

- Each released version of the package maps to a released version of the website. Users who read about feature "pkg::f()" on the website can be sure they'll have feature "pkg::f()" in their computer when I run `install.packages("pkg")`.

- Because the dev/ version of the website is hidden developers have a "staging" area to experiment without disrupting the working website, and without advertising features that may not be released.

To add an article (or any change) to the website of a package without releasing a new version to CRAN you may use this hack:

1. Checkout the tag of the latest release.
2. Checkout the new article from the main (or devel) branch.
3. Run [`pkgdown::deploy_to_branch()`](https://pkgdown.r-lib.org/reference/deploy_to_branch.html)
4. Don't commit anything (reset and clean as necessary), and move back to your main/devel branch.

Demo: https://youtu.be/uZnjkGwwG3w

**Comment by MonikaFu** [comment]
I see your point @maurolepore thanks. I might use the hack you mention to update part of the website. However, do you think that it might also be an idea to add a link to the dev version on the main website?

**Comment by maurolepore** [comment]
Yes, sounds like a good idea. If we give instructions to install the package from both CRAN and GitHub it makes sense to link the website where users can see the in-development features. I'm a bit hesitant because I don't see that as a common practice. But if it works for you go for it :-)

**Comment by MonikaFu** [comment]
I'll think about it. Also interested in @AlexAxthelm opinion about it :)

**Comment by AlexAxthelm** [comment]
🤔 I think the best option (but impractical) would be to have a version selector. I'm thinking something along the lines of [This header](https://www.postgresql.org/docs/13/app-psql.html) (but nicer looking, obviously 🙃). That would let us not only handle `dev`, and `prod`, but also old releases.

practically right now though, I would say that what is on the main site should be what's in the main release.

**Comment by MonikaFu** [comment]
Alright, thanks @AlexAxthelm . Let's keep it the way it is for now then and I will use @maurolepore hack whenever I need to update the website without a release.
